### ISSUE TITLE
New Term: Third-Party ABC

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#1]
For example, as in

```
Third-party repositories
Third-party software
```

Could you add this term into our styleguide? Thanks!

**Comment by sknorr** [comment]
According to the style guide, Merriam Webster is our reference for spellings. This word is defined on Merriam-Webster's website: [third-party](http://www.merriam-webster.com/dictionary/third-party) (as an adjective) & [third party](http://www.merriam-webster.com/dictionary/third party) (as a group of adjective and noun). Since this is both defined in our official source of spellings and there is nothing really unusual about this word, I think this one can be closed.
