### ISSUE TITLE
replace with v/ replace by

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#108]
What preposition to use?

[originally reported Apr 16, 2014 in Trello.]

**Comment by tahliar** [comment]
If this is still an unresolved question, you replace something _with_ something else, not _by_ something else.

If this is just a task tracker, don't mind me.

**Comment by sknorr** [comment]
It's an open question. But it appears to not be quite that easy: https://english.stackexchange.com/questions/151309/

**Comment by tahliar** [comment]
Well sure, "_replaced_ by" is correct in some forms (my favourite chocolate brand was replaced by an inferior brand), but the question here was for _replace_, which will always use _with_. ;)

**Comment by dariavladykina** [comment]
We still see this inconsistency in the style guide:
Remove or replace items that are irrelevant to your goal. For example, replace long
file names by shorter ones or remove a table column and replace it with [...] .

**Comment by tahliar** [comment]
> We still see this inconsistency in the style guide: Remove or replace items that are irrelevant to your goal. For example, replace long file names by shorter ones or remove a table column and replace it with [...] .

All our guides (including the Style Guide :laughing:) could definitely use a sweep to clean this up. I'm happy to help with that, or any similar kind of effort.

**Comment by dariavladykina** [comment]
Thanks Tahlia! So we can start the sweep :-) I'll do the style guide, and if you get a minute, you could start reviewing a book.
This is indeed a question of grammar, not our particular style and tone of voice. Therefore I wouldn't add this as a rule to the style guide, but our default should be this (quoting you):

As we generally aim for active voice, default to "with". There are times when passive voice is ok, in which case you might use "by". If in doubt, consult your nearest native speaker for what "sounds right".

**Comment by tahliar** [comment]
Ironically, it may end up being only the Style Guide itself that has this problem: 

* Fully checked doc-hpc, all clear.
* Fully checked doc-sleha, all clear.
* Did a quick check of doc-sle by grepping for "replace " (with a white space, to avoid `<replaceable>` tags), and didn't notice any issues. This is not a fool-proof check, however, because of the way we use hard line breaks mid-sentence for line length. We'll need to do a more thorough check but I think there's a decent chance we won't find any problems.
*  Did a quick grep check in doc-modular and didn't notice any issues.

These were the repos I have cloned on my machine, so I haven't checked any others yet, but so far it looks like it may be an isolated issue.

**Comment by dariavladykina** [comment]
Thanks for your help, Tahlia! I have checked doc-ses and doc-slesforsap, and all good there, too.
Now the style guide provides correct examples, too, so I believe we are good :-).

**Comment by dariavladykina** [comment]
Closing the issue as this has been merged.
