### ISSUE TITLE
Separate the "Format XML" section into "Editor" and "Formatting XML" 

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-styleguide#129]
The current "Format XML" section: https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-format-xml details information on best practice for how to setup your Editor, but mixed with content on Formatting XML.

These need to be split into two individual sections.

Should also think about having a corresponding section for ADOC.

**Comment by sknorr** [comment]
>on best practice for how to setup your Editor, but mixed with content on Formatting XML.

It does not define anything about the editor. It defines what the output document should look like.
Configuring the editor is currently left as an exercise to the reader (not ideal--but configuring individual editors is too specific for a style guide, so that needs to be documented elsewhere). In any case, I see nothing splittable.

* My understanding of the discussion today was:
  * Change the heading to something like "Source Formatting & Editor Settings", so people find it more easily.
  * Move the current content of this section into a subsection "XML"
  * Add an "AsciiDoc" subsection with new content

@taroth21 Does that match your ideas?

**Comment by dariavladykina** [comment]
Closing this as fixed.
