### ISSUE TITLE
Move DocBook Markup section to an appendix instead of including it in the Structure section

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#135]
5  Structure and Markup:
https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-structure

I'm wondering if we should move this to an appendix (or a separate guide as proposed in https://github.com/SUSE/doc-styleguide/issues/134). 

We could also shorten the chapter considerably by making sure we have examples for all sections covered in https://github.com/openSUSE/doc-kit/tree/master/docbook5-book and point to there instead of listing the examples within the style guide. (If possible, can we extend doc-kit to cover a setup with AsciiDoc files, too? Then we could do the same for the AsciiDoc chapter).  

I guess most people not familiar with XML would rather check out the example book files first and only refer to this guide if they want more information about certain elements. 

The following is probably out of scope here, but mentioning the idea anyway: 
Could we add a PDF and HTML output of the example book to the doc-kit repo (and keep it current as soon as the example files change)? So people would see how the example files are actually rendered.

**Comment by sknorr** [comment]
> I'm wondering if we should move this to an appendix (or a separate guide as proposed in #134).

To be honest, I would actually rather like to close this issue and use 134 for this entire discussion.

> We could also shorten the chapter considerably by making sure we have examples for all sections covered in https://github.com/openSUSE/doc-kit/tree/master/docbook5-book and point to there instead of listing the examples within the style guide.

Mmh, not so sure about that. I think most people will just delete the downstream example content (in fact, I hope that's what they do.) I also think there is a bit of value in having the TDG links and the explanations in addition to the elements.

The fact that you want to separate the structure from the markup again entirely makes me bleed a little internally, since combining them was one of the biggest changes I made in 2013. It also allowed for removing content that tried to describe proper visual markup (e.g. make this kind of content bold, underline this other kind of content, ...). Of course in 2013, we had a single documentation format and we only cared about doc team use, that has changed.

> (If possible, can we extend doc-kit to cover a setup with AsciiDoc files, too? Then we could do the same for the AsciiDoc chapter).

That is possible, but no one has done it. doc-kit is essentially a glorified downloader, not much more.

**Comment by jfaltenbacher** [comment]
> Could we add a PDF and HTML output of the example book to the doc-kit repo (and keep it current as soon as the example files change)? So people would see how the example files are actually rendered.

Sounds like a good suggestion to me
