### ISSUE TITLE
Wordy phrases should be listed in the style guide

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#17]
The style checker checks for wordy phrases. However, those are not listed in the style guide. That is bad because it takes away some of the authors's ability to check what style checker does.

**Comment by dariavladykina** [comment]
I would suggest creating such a list and adding it to the 'Language' section.

**Comment by dariavladykina** [comment]
Here's the list of wordy phrases + redundant phrases + unnecessary prepositions that we could include in the style guide.  
I wonder whether we should rather store this list somewhere and provide a link to this resource in the style guide?

actually → (delete)
as necessary  → (delete)
in fact → (delete)
if you want to → to
in order to → to
in order for → for
(as) of late → lately
as per → per
as a means of → to
as long as → if 
as to whether → whether
at a slow rate → slowly
at a quick rate → quickly
a majority of → most
a number of → some, a few, several
in accordance with → by, per, under
do damage to → damage
during the course of → during
in the course of → during, in, over, or while
for the duration of → during, through, for, or throughout
for the purpose(s) of → wordy for to or for
in terms of → regarding
make an effort → try
in an effort to → to
(the) majority of → most
previous to → before
prior to → before
take into consideration → consider
with the exception of → except (for), apart (from)
in the event that → if
have an impact on → affect, influence
have an effect on → affect, influence
the way in which → how
in a similar manner → similarly
give the opportunity to → let, allow
provide the ability to → let, allow
are representative of → represent
by means of → by, via
by the use of → using, with
by virtue of → because
by way of → by, via
in excess of → more than, over
in the absence of → without
as far as [X] is concerned → regarding
at the present time → now, currently
as of this writing → now, currently
at the time of publication → now, currently
at the current time → now, currently
at this point in time → now, currently
due to the fact that → because, since
despite the fact that → though, even though
be aware of the fact that → know, understand
in light of the fact that → because, considering
it’s important to note that → notably
in the direction of → toward
make a choice → choose, decide
(are) indicative of → reveal, show, suggest
on account of → because

**Redundant phrases**
still remain → remain
retain the same → retain
minor tweaks → tweaks
end result → result
both of them → both
trailing behind → trailing
factor that plays a role → factor
tailored to fit → tailored
specific details → details
check and see → check
good-quality (adj.) → quality
notification alert → notification (or alert)
in close proximity to → close to, near
debut of a new product → product debut
a little bit → a bit (or a little)

**Unnecessary prepositions**
click on → click
tap on → tap
raise up → raise
help out → help
last for [length of time] → last [length of time]
add together → add
send out → send

**Comment by tahliar** [comment]
> I wonder whether we should rather store this list somewhere and provide a link to this resource in the style guide?

I'd be open to this, but if we did I'd want to move the two terminology/language tables that are already in the style guide to the new place, too, rather than having them in different places. 

Alternatively, I'd also be fine with adding this list as a third table to Appendix A. Either option works for me, though I think maybe I have a slight preference for keeping everything together.

As for this list, it mostly looks good to me. A couple of thoughts: 

> (as) of late → lately

"Lately" is definitely better than "as of late", but I can't think of any reason for us to use "lately" in tech docs at all, so maybe it's better to just remove?

> (the) majority of → most

Duplicate (of "a majority of" further up).

> it’s important to note that → notably

I wonder if we would normally just use a Note admonition in this case? Not always, I guess :shrug:

> check and see → check

Could also use "verify". Generally I'd say "check if/whether X does Y" and "verify that X does Y", but to be honest you could also say "check that X does Y" without anyone noticing. 

> a little bit → a bit (or a little)

Could also say "some".

Related: the General Vocabulary table in the style guide has "with regard to" as an accepted phrase. It's certainly useful to call it out in comparison to the rejected versions, but it's also a wordier version of "regarding".

**Comment by jfaltenbacher** [comment]
I propose to have some of the words added to the stylechecker and then maybe after 6 months or so replace/add more words. This way, the writers are not bothered with the entire list and can learn step-by-step.

Can we add "desired" to the deprecated list, please?

**Comment by dariavladykina** [comment]
Closing the issue because the list has been added to the Vale style checker.

**Comment by dariavladykina** [comment]
Closing as the majority of the team already use VSCode with Vale integrated into it.
