### ISSUE TITLE
Console v/ terminal

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#178]
We should definitely have a preferred version of this in our terminology.

@lproven on the slacks:

> There used to be a clear distinction between "terminal" and "console" historically. It is confusing now because UNIX is a minicomputer OS and nobody makes minicomputers any more, and we all use microcomputers. In the early days, anyway, minicomputers generally did not have their own keyboard or mouse. They used only dumb terminals -- brainless keyboards and mice attached to serial lines, which could only display text and accept text input, but had no processor.
>The console was the special privileged terminal attached to the primary port on the host system and which displayed the bootup messages from the OS and so on. It was the master terminal, probably sat on top of the main computer, and you probably did not let users log in to it and run programs on it. They had ordinary unprivileged terminals, probably far away.

**Comment by dariavladykina** [comment]
Here are some insights:

https://en.opensuse.org/Terminal
https://en.opensuse.org/SDB:What_is_a_console
https://opensuse-guide.org/command.php

Also:
https://www.ibm.com/docs/en/linux-on-systems?topic=wysk-terminology-1
https://askubuntu.com/questions/506510/what-is-the-difference-between-terminal-console-shell-and-command-line
https://www.geeksforgeeks.org/difference-between-terminal-console-shell-and-command-line/

**Comment by dariavladykina** [comment]
doc-sle:
`console` has 353 mentions 
`terminal` has 185 mentions 
`shell` has 350 mentions

We'd need to also define `shell`

**Comment by janajaeger** [comment]
Hmmm. Ignore terminal and flip a coin?

**Comment by cwickert** [comment]
I'm afraid we can't ignore 'terminal', since this is what our GUI users will have launch and it's in the application's names: `xterm`, `gnome-terminal`, `xfce4-terminal`. Strictly speaking all of these names are wrong, because a terminal ia physical hardware as Liam pointed out. The apps are just terminal _emulators_. (For the record: KDE's terminal emulator is correctly called `konsole`).

To make things more confusing, we have 30 mentions of 'terminal console' (usually "Open a terminal console"), all in the storage guide. :-( This is definitely wrong, just use 'terminal' here.

Suggestion:
* Use 'terminal' by default. Ignore that these days, terminals are just terminal emulators.
* Only use 'console' for TTYs and possibly PTYs (means everything outside of X) and when talking about consoles (e.g. KVM's console or Xen's `xenconsoled`). These are not terminals as they are not 'generic'.
* Use 'shell' for programs that expose the input/output to the user (`bash`, `sh`, `zsh`) and when referring to the command prompt.

Overall, this would mean a big shift from console and shell towards 'terminal'.

**Comment by dariavladykina** [comment]
Terminology to be added to the SG:

`terminal` - text input/output environment where users interact with Linux and Linux applications. The default term to describe a text-only user interface.
`console` - a physical terminal, used to describe TTYs and PTYs and when talking about consoles (e.g. KVM's console or Xen's xenconsoled). 
`shell` - a command line interpreter, used to describe programs that expose the input/output to the user (bash, sh, zsh) and to refer to the command prompt.

**Comment by dariavladykina** [comment]
Closing as the update has been merged.
