### ISSUE TITLE
Clarify (over)use of "you" with examples

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#181]
on the sulks:

@dmpop 
> Our documentation is heavy on your: your server, your system, your network. I think it would benefit the overall style and voice if we use the instead (where it makes sense, of course). (edited) 
> Do you think it's worth adding to the style guide?

@sknorr 
> The style guide already contains something to the effect, not sure if it needs to be expanded:
>> Do not overuse “you.” It is often understood, especially in directions.

@fsundermeyer 
> "It is often understood, especially in directions."
> Me cannot parse this sentence

@dmpop
> understood -> implied
> directions -> instructions?

@sknorr 
> "It's often clear that the text is talking about the reader's dingsbums when it mentions "the dingsbums," especially within directions to the reader/procedural steps."
> The original wording may be too short for its own good, making it harder to understand. (..?)

@dmpop 
> I think a simple example would remedy the situation.
> Don't: Install X on your system
> Do: Install X on the system.

@sknorr
> I think the example is good, but there may need to be two examples here, one for when "you" is appropriate, one for when it isn't.

**Comment by dariavladykina** [comment]
Let us revamp these two paragraphs:

"Use the second person (“you”) to refer to the reader. Normally, the reader is the user or administrator who performs the actions described. Do not overuse “you" and "your". It is often implied who you are addressing in the instructions.
For example, instead of "Install X on your system" just say "Install X on the system".
Where possible, use active voice. In active voice, the subject of the sentence performs the action named by the verb. For example, “The root user performs administrative tasks” is active voice. “Administrative tasks are performed by the root user” is passive voice.

**Comment by janajaeger** [comment]
I like your suggestion @dariavladykina 
However we are still missing an example where the you/your might be appropriate. Any ideas?

**Comment by dariavladykina** [comment]
"You can upgrade your system by using `zypper dup`".
"To install all officially released patches that apply to your system, run: `zypper patch`".

**Comment by janajaeger** [comment]
> "You can upgrade your system by using `zypper dup`". "To install all officially released patches that apply to your system, run: `zypper patch`".

I like the second one.

**Comment by dmpop** [comment]
> Where possible, use active voice. In active voice, the subject of the sentence performs the action named by the verb. For example, “The root user performs administrative tasks” is active voice. “Administrative tasks are performed by the root user” is passive voice.

There is no need to explain the difference between active and passive voices, methinks.

**Comment by dariavladykina** [comment]
Closing the issue as this has been merged.
