### ISSUE TITLE
Revise the term 'drop-down box'

### ISSUE THREAD

**Issue by dariavladykina** [SUSE/doc-styleguide#206]
Does the term 'drop-down box' reflect the design of drop-down options in our docs? 
Will it make sense to update it to a more conventional term, 'drop-down list'?

**Comment by cwickert** [comment]
There are two questions to this:

1. Drop-down or dropdown? `drop-down` is the correct spelling, however `dropdown` is more popular.

2. Is it a box, list, or menu? We use `box` because this is what the widget is called in various GUI toolkits: Gtk has GtkComboBox and Qt QComboBox. However this is only relevant for programmers, users either use `menu` or `list`. According to Google Trends `menu` is more popular than `list` (in most countries) and almost nobody uses `box`, see https://trends.google.com/trends/explore?q=%22dropdown%20list%22,%22dropdown%20menu%22,%22dropdown%20box%22

Wikipedia uses `list`, see https://en.wikipedia.org/wiki/Drop-down_list

This being said, I'd vote for "drop-down list".

**Comment by cwickert** [comment]
Related term: "list box", currently defined as "noun; GUI element that is a list showing multiple elements even before interacting with it".

We would need to change both.
* If we go for `list`, `drop-down box` becomes `drop-down list` but `list box` becomes just `list`. Is this too confusing?
* If we go for `menu`, it's more distinct: `drop-down menu` vs. `list`.

**Comment by dariavladykina** [comment]
What I wanted to find out was whether there are indeed boxes with drop-down lists in GUI or elsewhere, so I understand there aren't, at least for users. 
In this case, how about replacing 'drop-down box' with `drop-down menu`, which would also cover the use case in the description: "if list entries start actions, use _menu_ instead".
I suggest keeping the `list box` as it is.

**Comment by dmpop** [comment]
I'm with Christoph on this one. I'd prefer to keep it simple and use _drop-down list_ as a term for list boxes and, um, lists.

**Comment by jfaltenbacher** [comment]
I am in favor of Daria's proposal. 
However, for list box we could do it like MS recommends:
When you need to help a customer interact with UI, refer to a list box by its label and the word list, not list box. 
See https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/l/list-box

Just for completeness: for dropdown they recommend the following:
https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/dropdown

**Comment by dariavladykina** [comment]
Thanks, I support MS recommendation on `list box`.

Let us then include the following:
When you need to help the user to interact with UI, refer to a list box by its label and the word 'list', not 'list box'.

**Comment by dariavladykina** [comment]
Merged, can be closed
