### ISSUE TITLE
Web UI Terminology: "screen" v/ "view" v/ "page" v/ "dialog" 

### ISSUE THREAD

**Issue by taroth21** [SUSE/doc-styleguide#53]
Which terms to use for pages/windows in Web UIs? ATM, we don't use consistent terminology in our docs.

Think of "screen" v/ "view" v/ "page" v/ "dialog". Also think of elements like "side bar" v/ "side pane" v/"navigation bar" v/ "navigation panel" etc. What about "tabs"? And does one click a "link" or click an "entry" in a "side bar" or "navigation panel"? ;) Also: How to call the first page of a Web UI? "start page"v/ "title page" v/"main view"?

**Comment by dmpop** [comment]
For my articles covering web-based apps, I stick to the following general rules:

 - The top element is **interface**. For example, a web app can have a user interface and administrator interface. In certain situations I use **area** instead of interface.
- Each interface consists of multiple **views** (a.k.a pages)
- **Sidebar** (not **pane**, as pane is part of a window)
- **Navigation bar** if it has a fixed position in the view or **navigation panel** if it's movable
- **Main interface** or **main area** for landing page, title page, main view, etc.

**Comment by dariavladykina** [comment]
Resolved in #202 , #213
