### ISSUE TITLE
Define use cases for command, option, and replaceable

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#63]
In table [id=tab.command_line](http://docserv.suse.de/documents/Styleguide/docu_styleguide/single-html/#tab.command_line) there is a list of descriptions about `command`, `option`, and `replaceable`.

However, it doesn't really explain *how* to use it consistently. It becomes especially complicated when combined with subcommands, options etc.  I tried to list the combinations:

1. Single command
   This is the easiest use case. Just use this:

```xml
<para>Run <command>ls</command> to... </para>
```

2.  Single command with arguments
   You can't place options *inside* the `<command>` tag because DocBook doesn't allow that in 5.x. The options can only be placed *after* the `<command>`:

```xml
<para>Run <command>ls</command> <option>-l</option> to... </para>
```

3. Single command with placeholders
  DocBook allows to insert a placeholder (`replaceable`) inside `<command>`. However, IMHO this should go outside (as with `option`):

```xml
<para>Run <command>ls</command> <replaceable>DIRECTORY</replaceable> to... </para>
```

4. Subcommands.
  This is the use case that needs some special love. Should the real executable be wrapped in `command` and subcommands outside? Or can be the command and its subcommands placed all inside? I'm not sure...

```xml
<para>Run <command>git checkout</command>  to... </para>
<!-- versus -->
<para>Run <command>git</command> <command>checkout</command>  to... </para>
```

Any ideas?

**Comment by sknorr** [comment]
Rather belated response. If the context is running text:

1. Yo.

2. I would not bother marking up the option specifically. `Run <command>ls -l</command> to [...]` is the best option imo: It's important to signalize that the option is part of the command (or at least belongs with the command). It's not important to specifically mark up the option.
I would only use the \<option/\> element if it stands alone, such as in `To use a listing format, add the option <option>-l</option>.`

3. I disagree with the "imho" here, because just as in (2.), it's important that command and replaceable are marked up together.
So, a clear vote for `<command>ls <replaceable>DIRECTORY</replaceable></command>`.

4. Yet again, same as (2.) and (3.): `<command>git checkout</command>` belongs together.


Exception: If the context is that you're trying to formulate a command synopsis, you should of course mark up all these items separately.

**Comment by dariavladykina** [comment]
Stefan's input has been incorporated to DSG, closing this as completed.
