### ISSUE TITLE
Document documentation.suse.com URL & how to link there

### ISSUE THREAD

**Issue by tomschr** [SUSE/doc-styleguide#94]
Our documentation is now hosted under documentation.suse.com. We should state the preferred URL in our styleguide.

**Update 2021-10-26:**  also state in the styleguide how we deal with abbreviated URLs like `doc.suse.com`/`docs.suse.com` (avoided or allowed).

(Original discussion from https://github.com/SUSE/doc-slesforsap/pull/17#discussion_r346740855)

**Comment by sknorr** [comment]
@taroth21 on Rocketchat, regarding links to doc.suse.com pages:

> regarding www.suse.com/documentation -> documentation.suse.com in our docs: after thinking and re-thinking about it multiple times, I consider it best not to use any entities at all, but use the plain text URLs for the following reasons:
> - using entities for parts of URLs (&dsc-sles-15;/html/SLES-all/cha-upgrade-offline.html#sec-update-registersystem) makes it harder to copy and paste URLs into the sources and harder to update them in one go if needed
> - entities are resolved to plain text during translations, so if a URL needs to be updated in 'master' and the 'translation' branches for any reasons, you can at least expect them to be the same
> - we mostly need to point to URLs for specific versions anyway
> - also decided to use the single-html ones because they show directly in which book the content is located

**Comment by sknorr** [comment]
Tanja's evolved ideas (from https://github.com/SUSE/doc-sle/commit/035e7499c1d84305ac04c78b8ed04cd600aef1da):

> *  avoid entities for URLs (entities for parts of the URL make it harder to copy/paste/replace complete URLs, plus they will be resolved during translation anyway)
>   -> this way the URLs are the same in the English versions and translation branches and can replaced the same way if needed
> *  using upcoming 15-SP2 URLs (they will only work after FCS, but it prevents us from updating them in the translation branches after FCS)
> * use links to html instead of single-html (shorter download times, SEO)
> * use descriptive text for links to mention book name (in case deeplink is broken, plus better accessibility)

**Comment by cwickert** [comment]
For reference, here is the corresponding commit for doc-sle: https://github.com/SUSE/doc-sle/commit/035e7499

**Comment by cwickert** [comment]
In the SLE writers call yesterday, we agreed to use full URLs for easier copy & paste.

Can we close this now or should this be documented in the Style Guide?

**Comment by cwickert** [comment]
Another proposal: https://confluence.suse.com/display/documentation/A+Proposal+for+Solving+the+mid-2020+SUSEan+Missing+URL+Crisis

**Comment by cwickert** [comment]
What is left to do here?

Let's ignore Stefan's proposal outlined in confluence page above. It's too complex and tries to solve a problem we hardly ever have. We only became aware of it when we moved servers and changed the URL, but I don't expect us to do this again any time soon.

So IHMO all that is left is some addition to the Style Guide with the following information:

* documentation.suse.com is the authoritative URL for all our documentation.
  * doc.suse.com is shorter and the redirect works, but we write out documentation.suse.com for SEO reasons.
* use complete URLs instead of entities to allow for easy copy & paste
* link html versions instead of single-html
* Explain version specific links and the generic redirects: 
  * both
https://documentation.suse.com/sles/15/html/SLES-all/art-modules.html and
https://documentation.suse.com/sles-15/html/SLES-all/article-modules.html redirect to the latest SLE 15 release, currently to
https://documentation.suse.com/sles/15-SP3/html/SLES-all/article-modules.html
  * Prefer generic links, only use version-specific links if you have to (e.g. if the information is version-specific and/or needs to match the version of the guide you are linking from).

Did I miss something? Who's willing to write this?

**Comment by dariavladykina** [comment]
This has been implemented, closing the issue.
